django_CCOS/urls.py
from django.contrib import admin
from django.urls import path

# 用于 include 其他模板所在的 url
from django.conf.urls import include

# 用于 图片 静态存储
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supplier.urls')),
    path('customer/', include('customer.urls')),
    path('', include('product.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import show_product, show_order, get_order, search_orders, cancel_order, search_categories, \
    order_area_charts, carrier_charts

app_name = 'product'
urlpatterns = [
    path('product/', show_product, name='show_product'),
    path('order/', show_order, name='show_order'),
    path('get_order/<slug:product_id>/', get_order, name='get_order'),
    path('search_orders/', search_orders, name='search_orders'),
    path('cancel_order/<slug:order_id>/', cancel_order, name='cancel_order'),
    path('search_categories/', search_categories, name='search_categories'),
    path('order_charts/', order_area_charts, name='order_charts'),
    path('carrier_charts', carrier_charts, name='carrier_charts'),
]

product/models.py
from django.db import models
from supplier.models import Category, Supplier
from carrier.models import Carrier
from customer.models import Customer
from django.urls import reverse


class Product(models.Model):
    product_id = models.AutoField(primary_key=True, verbose_name='产品ID')
    category = models.ForeignKey(Category, models.CASCADE, null=True, verbose_name='类别ID')
    product_name = models.CharField(max_length=255, verbose_name='产品名称', null=True)
    product_quantity = models.CharField(max_length=255, verbose_name='单位数量', null=True)
    product_price = models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价', null=True)
    product_photo = models.ImageField(upload_to='images/product', null=True, verbose_name='商品照片')
    product_inventory = models.SmallIntegerField(verbose_name='库存量', null=True)
    product_orderquantity = models.SmallIntegerField(verbose_name='订购量', null=True)
    product_reorderquanatity = models.SmallIntegerField(verbose_name='再订购量', null=True)
    product_status = models.IntegerField(choices=[(0, '中止'), (1, '在售')], verbose_name="状态", null=True)
    product_detail = models.TextField(null=True, verbose_name='商品描述')

    class Meta:
        ordering = ['product_id']
        db_table = 'product'
        verbose_name = "商品信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.product_name

    def get_order_url(self):
        return reverse("product:get_order", kwargs={'product_id': self.product_id})


class Information(models.Model):
    info_productbarch_id = models.IntegerField(verbose_name='产品批次ID', null=True)
    info_product = models.ForeignKey(Product, models.CASCADE, verbose_name='产品ID', null=True)
    info_productiondate = models.DateTimeField(verbose_name='生产日期', null=True)
    info_expirationdate = models.DateTimeField(verbose_name='保质期', null=True)

    class Meta:
        unique_together = ('info_productbarch_id', 'info_product')
        db_table = 'Information'
        verbose_name = "生产信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.info_productbarch_id)


class Order(models.Model):
    order_id = models.AutoField(primary_key=True, verbose_name='订单ID')
    order_customer_id = models.ForeignKey(Customer, models.CASCADE, null=True, verbose_name='客户ID')
    order_carrier_id = models.ForeignKey(Carrier, models.CASCADE, null=True, verbose_name='运货商ID')
    order_orderdate = models.DateTimeField(verbose_name='订购日期', null=True)
    order_senddate = models.DateTimeField(verbose_name='发货日期', null=True, blank=True)
    order_receivedate = models.DateTimeField(verbose_name='到货日期', null=True, blank=True)
    order_confirmdate = models.DateTimeField(verbose_name='货款确认日期', null=True, blank=True)
    order_price = models.CharField(max_length=255, verbose_name='订单价格', null=True)
    order_charge = models.CharField(max_length=255, verbose_name='运费', null=True, blank=True)
    order_C_name = models.CharField(max_length=255, verbose_name='货主名称', null=True)
    order_C_Address = models.CharField(max_length=255, verbose_name='货主地址', null=True)
    order_C_City = models.CharField(max_length=255, verbose_name='货主城市', null=True)
    order_C_Area = models.IntegerField(
        choices=[(0, '华北'), (1, '东北'), (2, '华东'), (3, '华西'), (4, '华中'), (5, '华南'), (6, '西南'), (7, '西北')],
        verbose_name="地区", default=1, null=True)
    order_C_PostalCode = models.CharField(max_length=255, verbose_name='货主邮政编码', null=True)
    order_C_Country = models.CharField(max_length=255, verbose_name='货主国家', null=True)
    order_Payway = models.CharField(max_length=255, verbose_name='支付方式', null=True, blank=True)
    order_Insurance = models.IntegerField(choices=[(0, '不使用保险'), (1, '使用保险')], verbose_name="保险信息", default=1,
                                          null=True)
    product = models.ForeignKey(Product, models.SET_NULL, null=True, verbose_name='产品ID')

    class Meta:
        ordering = ['order_id']
        db_table = 'Order'
        verbose_name = "订单信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.order_id)


class OrderDetail(models.Model):
    od_id = models.ForeignKey(Order, models.CASCADE, null=True, verbose_name='订单ID')
    od_product_id = models.ForeignKey(Product, models.CASCADE, null=True, verbose_name='产品ID')
    od_weight = models.SmallIntegerField(verbose_name='重量', null=True)
    od_quantity = models.SmallIntegerField(verbose_name='数量', null=True)
    od_notes = models.TextField(verbose_name='备注', null=True)

    class Meta:
        ordering = ['od_id']
        db_table = 'OrderDetail'
        verbose_name = "订单明细"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.od_id)

product/views.py
import random
from pyecharts import options as opts
from django.db.models import Count, IntegerField, When, Case
from pyecharts.charts import Bar, Pie, Line
from .models import Product, Order, OrderDetail
from customer.models import Customer
from supplier.models import Category
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from datetime import datetime


def show_product(request):
    template_name = 'product/product_list.html'
    context = {
        'category_with_product_list': Category.objects.all(),
        'product_list': Product.objects.all(),
    }

    return render(request, template_name, context)


def show_order(request):
    if not request.session.get('is_login', None):
        messages.warning(request, "请先登录顾客账户~")
        return redirect('/customer/login/')

    user_id = request.session['user_id']

    OrderAll = Order.objects.filter(order_customer_id=user_id)
    total_price = 0
    total_charge = 0
    template_name = 'product/my_order.html'

    for item in OrderAll:
        total_price += item.product.product_price

    basic1_charge = 5
    basic2_charge = 10
    basic_else_charge = 3

    for item in OrderAll:
        orderDetail = OrderDetail.objects.filter(od_id=item.order_id).first()
        if item.product.category.category_id == '1':  # 谷物(长期）
            total_charge += int(basic1_charge + 0.25 * (pow(orderDetail.od_weight - 5, 2)))
        elif item.product.category.category_id == '2':  # 水产(短期)
            total_charge += int(basic2_charge + 0.5 * (pow(orderDetail.od_weight - 5, 2)))
        else:  # 其他(期限中等)
            total_charge += int(basic_else_charge + 0.3 * (pow(orderDetail.od_weight - 5, 2)))

    context = {
        'order_list': OrderAll,
        'total_price': total_price,
        'total_charge': total_charge,
    }
    return render(request, template_name, context)


def get_order(request, product_id):
    if not request.session.get('is_login', None):
        messages.warning(request, "请先登录顾客账户~")
        return redirect('/customer/login/')

    product = get_object_or_404(Product, product_id=product_id)
    user_id = request.session['user_id']

    try:
        user = Customer.objects.filter(customer_id=user_id).first()
        if user.address is None:
            messages.warning(request, "你还未填写地址信息哦~")
            return redirect('product:show_order')
        order = Order.objects.create(
            order_customer_id=user,
            order_C_name=user.customer_name,
            order_C_Address=user.address.customer_address,
            order_C_City=user.address.customer_city,
            order_C_Area=user.address.customer_area,
            order_C_PostalCode=user.address.customer_postalcode,
            order_C_Country=user.address.customer_country,
            order_orderdate=datetime.now(),
            product=product,
        )
        order.order_price = order.product.product_price
        product.product_inventory -= 1
        product.save()
        order.save()

        weight = random.randint(1, 5)
        quantity = 1
        notes = "无备注"
        orderDetail = OrderDetail.objects.create(
            od_id=order,
            od_product_id=product,
            od_weight=weight,
            od_quantity=quantity,
            od_notes=notes,
        )

        orderDetail.save()
        messages.success(request, '下单成功，请支付 {} 元'.format(order.order_price))
        return redirect("product:show_order")

    except ObjectDoesNotExist:
        messages.warning(request, "你还没有订单喵~")
        return redirect("product:show_order")


def search_orders(request):
    order_id = request.GET.get('order_id', '')
    try:
        order = Order.objects.get(order_id=order_id)
        return render(request, 'product/order_detail.html', {'order': order})
    except Order.DoesNotExist:
        messages.warning(request, "订单不存在喵~")
        return redirect("product:show_order")


def cancel_order(request, order_id):
    item = Order.objects.filter(order_id=order_id).first()
    if item is not None:
        item.delete()
    return redirect('product:show_order')


def search_categories(request):
    category_name = request.GET.get('category_name', '')
    if category_name:
        category = Category.objects.filter(category_name__icontains=category_name)
    else:
        category = Category.objects.all()
    context = {
        'category_with_product_list': category,
        'product_list': Product.objects.all(),
    }
    return render(request, 'product/product_list.html', context)


def order_area_charts(request):
    objs_hb = Order.objects.filter(order_C_Area="0")
    objs_db = Order.objects.filter(order_C_Area="1")
    objs_hd = Order.objects.filter(order_C_Area="2")
    objs_hx = Order.objects.filter(order_C_Area="3")
    objs_hz = Order.objects.filter(order_C_Area="4")
    objs_hn = Order.objects.filter(order_C_Area="5")
    objs_xn = Order.objects.filter(order_C_Area="6")
    objs_xb = Order.objects.filter(order_C_Area="7")
    order_area = ["华北", "东北", "华东", "华西", "华中", "华南", "西南", "西北"]
    order_data = [objs_hb.count(), objs_db.count(), objs_hd.count(), objs_hx.count(), objs_hz.count(),
                  objs_hn.count(),
                  objs_xn.count(), objs_xb.count()]
    pie_type = Pie()
    pie_type.add(
        "",
        [list(z) for z in zip(order_area, order_data)],
        center=["35%", "50%"],
    )
    pie_type = pie_type.render_embed()
    bar_type = Bar()
    bar_type.add_xaxis(order_area)
    bar_type.add_yaxis("订单数", order_data)
    bar_type = bar_type.render_embed()
    context = {'pie_type': pie_type, 'bar_type': bar_type}

    return render(request, 'product/order_area.html', context)


def carrier_charts(request):
    season_data = Order.objects.annotate(season=Case(
        When(order_senddate__month__in=[3, 4, 5], then=1),
        When(order_senddate__month__in=[6, 7, 8], then=2),
        When(order_senddate__month__in=[9, 10, 11], then=3),
        When(order_senddate__month__in=[12, 1, 2], then=4),
        output_field=IntegerField()
    )).values('season').annotate(count=Count('order_id')).order_by('season')
    season_bar = (
        Bar()
        .add_xaxis(['春季', '夏季', '秋季', '冬季'])
        .add_yaxis('订单量', [season['count'] for season in season_data])
        .set_global_opts(title_opts=opts.TitleOpts(title='不同季节的运货量统计'))
    )
    objs_hb = Order.objects.filter(order_C_Area="0")
    objs_db = Order.objects.filter(order_C_Area="1")
    objs_hd = Order.objects.filter(order_C_Area="2")
    objs_hx = Order.objects.filter(order_C_Area="3")
    objs_hz = Order.objects.filter(order_C_Area="4")
    objs_hn = Order.objects.filter(order_C_Area="5")
    objs_xn = Order.objects.filter(order_C_Area="6")
    objs_xb = Order.objects.filter(order_C_Area="7")
    order_area = ["华北", "东北", "华东", "华西", "华中", "华南", "西南", "西北"]
    order_data = [objs_hb.count(), objs_db.count(), objs_hd.count(), objs_hx.count(), objs_hz.count(),
                  objs_hn.count(),
                  objs_xn.count(), objs_xb.count()]
    line_type = Line()
    line_type.add_xaxis(order_area)
    line_type.add_yaxis("订单量", order_data, is_smooth=True)
    line_type.set_global_opts(title_opts=opts.TitleOpts(title="不同地区运货量统计"))
    context = {
        'line_type': line_type.render_embed(),
        'season_chart': season_bar.render_embed(),
    }
    return render(request, 'product/order_season.html', context)

templates/product/my_order.html
{% extends 'product/product_base.html' %}
{% block preproduct %}
<div class="container headerdiv">
    <h3 class="headertext" align="center">我的订单</h3>
</div>
{% endblock %}
{% block product_content %}

<style>
    	.table th, .table td {
    		text-align: center;
    		vertical-align: middle!important;
    	}
    	.form-group {
    	    width: 20%;
        }

        #submitOrderBtn {
            width: 150px;
            margin: 0 auto;
       }
</style>

<div class="container jumbotron">
    <form method="GET" action="{% url 'product:search_orders' %}">
        <div class="form-group">
            <label for="order_id">订单:</label>
            <input type="text" class="form-control" id="order_id" name="order_id">
        </div>
        <button type="submit" class="btn btn-primary">搜索</button>
    </form>

    <div class="table-responsive text-nowrap">

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">序号</th>
                <th scope="col">客户名称</th>
                <th scope="col">商品</th>
                <th scope="col">价格</th>
            </tr>
            </thead>
            <tbody>
            {% for order in order_list %}
            <tr>
                <td>{{ order.order_id }}</td>
                <td>{{ order.order_customer_id.customer_name }}</td>
                <td>{{ order.product.product_name }}</td>
                <td>{{ order.product.product_price }}元</td>
                <td><a href="{% url 'product:cancel_order' order.order_id %}">取消订单</a></td>
            </tr>
            {% empty %}
            {% endfor %}
            </tbody>
        </table>
        <p>产品总价: {{ total_price }}</p>
        <p>总运费:{{total_charge}}</p>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <button id="submitOrderBtn" class="btn btn-primary btn-lg btn-block">提交订单</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var submitOrderBtn = document.getElementById("submitOrderBtn");
        submitOrderBtn.addEventListener("click", function() {
            alert("订单提交成功！");
            window.location.href = "{% url 'product:show_product' %}";
        });
    });

</script>

{% endblock %}

templates/product/order_area.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div style="display: inline-block; width: 50%;">
            {{ pie_type|safe }}
        </div>
        <div style="display: inline-block; width: 50%;">
            {{ bar_type|safe }}
        </div>
    </div>
{% endblock %}

templates/product/order_detail.html
{% extends 'product/product_base.html' %}
{% block preproduct %}
<div class="container headerdiv">
    <h3 class="headertext" align="center">订单详情</h3>
</div>
{% endblock %}
{% block product_content %}

<div class="table-responsive text-nowrap">

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">序号</th>
            <th scope="col">商品</th>
            <th scope="col">单位数量</th>
            <th scope="col">价格</th>
            <th scope="col">货主地址</th>
            <th scope="col">订购日期</th>
            <th scope="col">发货日期</th>
            <th scope="col">运货商名称</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ order.order_id }}</td>
            <td>{{ order.product.product_name }}</td>
            <td>{{ order.product.product_quantity }}</td>
            <td>{{ order.product.product_price }}元</td>
            <td>{{ order.order_C_Address }}</td>
            <td>{{ order.order_orderdate }}
            <td>{{ order.order_senddate }}</td>
            <td>{{ order.product.category.supplier.supplier_name}}</td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/product/order_season.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div style="display: inline-block; width: 50%;">
            {{ line_type|safe }}
        </div>
        <div style="display: inline-block; width: 50%;">
            {{ season_chart|safe }}
        </div>
    </div>
{% endblock %}

templates/product/product_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preproduct %}{% endblock %}
    {% block product_content %}{% endblock %}

  </div>

</div>

{% endblock %}

templates/product/product_detail.html
{% extends 'product/product_base.html' %}

{% block content %}
Dish details
{% endblock %}

templates/product/product_list.html
<style>
    .product-price {
        text-align: center;
        font-size: 16px;
    }


</style>

{% extends 'product/product_base.html' %}

{% block product_content %}

<form method="GET" action="{% url 'product:search_categories' %}">
    <div class="form-group">
        <label for="category_name">类别搜索:</label>
        <input type="text" class="form-control" id="category_name" name="category_name">
    </div>
    <button type="submit" class="btn btn-primary">搜索</button>
</form>
{% for i in category_with_product_list %}
<div class="container headerdiv">
    <h3 class="headertext" align="center" id="{{i.category_id}}">『{{ i.category_name }}』</h3>
</div>
<div>
    <div class="container">
        <div class="row">

            {% for j in product_list %}
            {% if j.category == i %}
            <div class="col-lg-4 d-flex align-items-stretch">
                <div class="card cardmodify cardbackground" style="width: 35rem;">
                    <div class="card-header">
                        <h5><b>{{ j.product_name }}</b></h5>
                    </div>
                    <img class="card-img-top" src="{{ j.product_photo.url }}" alt="Card image cap" height="200px"
                         width="100px">
                    <div class="card-body d-flex flex-column" data-cat="{{ i.dish_category }}">
                        <p class="card-text">单位数量:{{ j.product_quantity }}</p>
                        <p class="card-text">库存量:{{ j.product_inventory }}</p>
                        <p class="card-text">单价:{{ j.product_price }}</p>

                        <div class="align-self-end container">
                            <a class="btn btn-success btn-sm addtocartbutton"
                               href="{{ j.get_order_url }}"><font size="3px">加入订单！</font></a>
                        </div>

                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}